-- 1. procedure_categories
create table procedure_categories (
    id bigint generated by default as identity,
    category_name varchar(255) not null,
    constraint pk_procedure_categories primary key (id),
    constraint uq_procedure_categories_name unique (category_name),
    constraint chk_procedure_categories_name_not_empty check (char_length(trim(category_name)) > 0)
);

-- 2. channel_types
create table channel_types (
    id bigint generated by default as identity,
    code varchar(20) not null,
    channel_name varchar(100) not null,
    constraint pk_channel_types primary key (id),
    constraint uq_channel_types_code unique (code),
    constraint uq_channel_types_channel_name unique (channel_name),
    constraint chk_channel_types_code_not_empty check (char_length(trim(code)) > 0),
    constraint chk_channel_types_channel_name_not_empty check (char_length(trim(channel_name)) > 0)
);

-- 3. users
create table users (
    id bigint generated by default as identity,
    full_name varchar(100) not null,
    user_type varchar(20) not null,
    login varchar(100),
    password_hash varchar(255),
    failed_login integer not null default 0,
    locked_until timestamp,
    created_at timestamp not null default current_timestamp,
    constraint pk_users primary key (id),
    constraint uq_users_login unique (login),
    constraint chk_users_user_type check (user_type in ('master', 'client')),
    constraint chk_users_name_not_empty check (char_length(trim(full_name)) > 0),
    constraint chk_users_name_format check (full_name ~ '^[А-Яа-яЁёA-Za-z]+([ -][А-Яа-яЁёA-Za-z]+)*$'),
    constraint chk_users_login_not_empty check (login is null or char_length(trim(login)) > 0),
    constraint chk_users_password_hash_not_empty check (password_hash is null or char_length(trim(password_hash)) > 0),
    constraint chk_users_failed_login check (failed_login between 0 and 3),
    constraint chk_users_auth_data check (
            (
                user_type = 'master'
                and login is not null
                and password_hash is not null
            )
            or
            (
                user_type = 'client'
                and login is null
                and password_hash is null
            )
    ),
    constraint chk_users_login_lock check (
            (
                user_type = 'client'
                and failed_login = 0
                and locked_until is null
            )
            or
            (
                user_type = 'master'
                and failed_login < 3
                and locked_until is null
            )
            or
            (
                user_type = 'master'
                and failed_login = 3
                and locked_until is not null
            )
    )
);

-- 4. procedures
create table procedures (
    id bigint generated by default as identity,
    category_id bigint not null,
    master_user_id bigint not null,
    procedure_name varchar(255) not null,
    description varchar(500),
    price decimal(10, 2) not null,
    duration_minutes integer not null,
    status varchar(20) not null default 'available',
    created_at timestamp not null default current_timestamp,
    constraint pk_procedures primary key (id),
    constraint fk_procedures_categories foreign key (category_id) references procedure_categories(id)
        on delete restrict
        on update cascade,
    constraint fk_procedures_masters foreign key (master_user_id) references users(id)
        on delete restrict
        on update cascade,
    constraint uq_procedures_category_name unique (category_id, procedure_name),
    constraint chk_procedures_status check (status in ('available', 'unavailable')),
    constraint chk_procedures_price check (price >= 0),
    constraint chk_procedures_duration_minutes check (duration_minutes > 0),
    constraint chk_procedures_name_not_empty check (char_length(trim(procedure_name)) > 0),
    constraint chk_procedures_name_format check (procedure_name ~ '^[А-Яа-яЁёA-Za-z0-9 .,+()/-]+$')
);

-- 5. schedules
create table schedules (
    id bigint generated by default as identity,
    master_user_id bigint not null,
    date_from date not null,
    date_to date not null,
    created_at timestamp not null default current_timestamp,
    constraint pk_schedules primary key (id),
    constraint fk_schedules_masters foreign key (master_user_id) references users(id)
        on delete restrict
        on update cascade,
    constraint chk_schedules_date check (date_from <= date_to)
);

-- 6. schedule_days
create table schedule_days (
    id bigint generated by default as identity,
    schedule_id bigint not null,
    work_date date not null,
    is_working boolean not null default true,
    start_time time,
    end_time time,
    created_at timestamp not null default current_timestamp,
    constraint pk_schedule_days primary key (id),
    constraint fk_schedule_days_schedule foreign key (schedule_id) references schedules(id)
        on delete restrict
        on update cascade,
    constraint uq_schedule_days_schedule_date unique (schedule_id, work_date),
    constraint chk_schedule_days_working_time check (
        (is_working = true and start_time is not null and end_time is not null and start_time < end_time)
        or
        (is_working = false and start_time is null and end_time is null)
    )
);

-- 7. unavailable_periods
create table unavailable_periods (
    id bigint generated by default as identity,
    schedule_day_id bigint not null,
    start_time time not null,
    end_time time not null,
    reason varchar(255),
    created_at timestamp not null default current_timestamp,
    constraint pk_unavailable_periods primary key (id),
    constraint fk_unavailable_periods_schedule_days foreign key (schedule_day_id) references schedule_days(id)
        on delete restrict
        on update cascade,
    constraint chk_unavailable_periods_time check (start_time < end_time),
    constraint uq_unavailable_periods_schedule_day_time unique (schedule_day_id, start_time, end_time)
);

-- 8. bookings
create table bookings (
    id bigint generated by default as identity,
    procedure_id bigint not null,
    schedule_day_id bigint not null,
    client_user_id bigint not null,
    start_time time not null,
    end_time time not null,
    fixed_price decimal(10, 2) not null,
    status varchar(20) not null default 'created',
    access_token varchar(255) not null,
    data_consent boolean not null,
    created_at timestamp not null default current_timestamp,
    canceled_at timestamp,
    constraint pk_bookings primary key (id),
    constraint fk_bookings_procedures foreign key (procedure_id) references procedures(id)
        on delete restrict
        on update cascade,
    constraint fk_bookings_schedule_days foreign key (schedule_day_id) references schedule_days(id)
        on delete restrict
        on update cascade,
    constraint fk_bookings_clients foreign key (client_user_id) references users(id)
        on delete restrict
        on update cascade,
    constraint chk_bookings_status check (status in ('created', 'canceled', 'completed', 'no_show')),
    constraint chk_bookings_time_range check (start_time < end_time),
    constraint chk_bookings_fixed_price check (fixed_price >= 0),
    constraint uq_bookings_access_token unique (access_token),
    constraint uq_bookinf_id_param_booking unique (id, schedule_day_id, start_time, end_time),
    constraint chk_bookings_access_token check (char_length(trim(access_token)) > 0),
    constraint chk_bookings_data_consent check (data_consent = true),
    constraint chk_bookings_canceled_at check (
            (status = 'canceled' and canceled_at is not null)
            or
            (status in ('created', 'completed', 'no_show') and canceled_at is null)
    )
);
create index idx_bookings_schedule_day_status_time on bookings (schedule_day_id, status, start_time, end_time)
where status = 'created';

-- 9. notifications
create table notifications (
    id bigint generated by default as identity,
    booking_id bigint not null,
    recipient_user_id bigint not null,
    notification_type varchar(50) not null,
    message_text text not null,
    status varchar(20) not null default 'created',
    created_at timestamp not null default current_timestamp,
    sent_at timestamp,
    constraint pk_notifications primary key (id),
    constraint fk_notifications_bookings foreign key (booking_id) references bookings(id)
        on delete restrict
        on update cascade,
    constraint fk_notifications_users foreign key (recipient_user_id) references users(id)
        on delete restrict
        on update cascade,
    constraint uq_notifications_booking_recipient_type unique (booking_id, recipient_user_id, notification_type),
    constraint chk_notifications_type check (
        notification_type in (
            'master_booking_created',
            'client_booking_created',
            'master_booking_canceled',
            'client_booking_canceled',
            'client_booking_reminder'
        )
    ),
    constraint chk_notifications_status check (
        status in ('created', 'sent', 'delivered', 'error')
    ),
    constraint chk_notifications_message_text_not_empty check (char_length(trim(message_text)) > 0),
    constraint chk_notifications_sent_at check (
        (status in ('created', 'error') and sent_at is null)
        or
        (status in ('sent', 'delivered') and sent_at is not null)
    )
);
create index idx_notifications_status_created_at on notifications (status, created_at);

-- 10. contact_channels
create table contact_channels (
    id bigint generated by default as identity,
    user_id bigint not null,
    channel_type_id bigint not null,
    value varchar(255) not null,
    status varchar(20) not null default 'active',
    created_at timestamp not null default current_timestamp,
    constraint pk_contact_channels primary key (id),
    constraint fk_contact_channels_users foreign key (user_id) references users(id)
        on delete restrict
        on update cascade,
    constraint fk_contact_channels_type foreign key (channel_type_id) references channel_types(id)
        on delete restrict
        on update cascade,
    constraint chk_contact_channels_status check (status in ('active', 'inactive')),
    constraint chk_contact_channels_value check (char_length(trim(value)) > 0),
    constraint uq_contact_channels_user_type unique (user_id, channel_type_id),
    constraint uq_contact_channels_type_value unique (channel_type_id, value)
);
create index idx_contact_channels_user_status on contact_channels (user_id, status);